### ISSUE TITLE
Input Types

### ISSUE THREAD

**Issue by zombor** [granateio/granate#24]
I'm wondering what the best practices for using input objects for mutations is. I'm not sure if I'm doing something wrong, or if there isn't good support in this package's generated files for it.

My schema:

```
type TransactionBudgetEdgeInput {
  amount: Int!
  budget: ID!
}

type Mutation {
  addTransaction(at: String!, payee: String!, account: String!, amount: Int!, budgets: [TransactionBudgetEdgeInput]): Transaction
}
```

The code generated in `schema/` doesn't seem to work with this. In the `Resolve` function for `addTransaction`, the `params.Args["budgets"]` call ends up returning a nil map.

I was able to fix this by redefining `transactionBudgetEdgeInputDefinition` as a `graphql.NewInputObject` along with the appropriate fields. This starts populating `params.Args["budgets"]` with the proper data from my input.

However the datatype that `mapstructure.Decode` is decoding into is a `[]TransactionBudgetEdgeInputInterface`. This isn't actually a concrete type so the decoding just ends up being a bunch of nil interfaces.

Are there any recommendations for this? It looks like I'll need to make a new type in the `schema` package that satisfies the `TransactionBudgetEdgeInputInterface` interface and decode the data into that. How do you handle this?

**Comment by Nohac** [comment]
Your `TransactionBudgetEdgeInput` needs to be of type `input` and not `type`:
```diff
- type TransactionBudgetEdgeInput {
+ input TransactionBudgetEdgeInput {
  amount: Int!
  budget: ID!
}
```
This is because `input` types only support primitive graphql types, so it can safely be translated into a struct, while `type` can be more complex, so they resolve into interfaces that you need to implement.

I understand that this can be confusing, the documentation of this library isn't exactly great atm.
Pleas let me know if you have any more questions.

**Comment by zombor** [comment]
Ah yeah, got it! I'm still pretty new to graphql and didn't know about the `input` keyword.

Thanks!
